### ISSUE TITLE
無法正確執行

### ISSUE THREAD

**Issue by MatsuiLin101** [twtrubiks/PttAutoLoginPost#1]
這個版本的code跟DEMO影片的code不一樣，clone下來之後無法直接執行

1.
第一行似乎要加上
#coding=utf-8

2.
做了1之後，可以登入到PTT，但在發文時會出錯
Traceback (most recent call last):
  File "PttAuto.py", line 121, in <module>
    main()
  File "PttAuto.py", line 116, in main
    ptt.post('test', '發文文字測試', '這是一篇測試,哇哈哈')
  File "PttAuto.py", line 94, in post
    self._telnet.write(title.encode('big5') + b'\r\n')
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe7 in position 0: ordinal not in range(128)

**Comment by twtrubiks** [comment]
請問你使用的python版本是?

影片的code是舊的沒錯，新版的我也有測試過能work。

所以想詢問一下你的python版本

**Comment by MatsuiLin101** [comment]
原來是python版本的關係，最近剛開始學，抱歉沒注意到。

我在ubuntu的python版本如下：
Python 2.7.12 (default, Nov 19 2016, 06:48:10)
Python 3.5.2 (default, Nov 17 2016, 17:05:23)

直接輸入python PttAuto.py會無法執行
改成ˊ輸入python3 PttAuto.py就可以了

**Comment by twtrubiks** [comment]
好哦~
